apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"webapp:latest","namespace":"anjulakshmi-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"webapp\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2025-11-02T10:06:43Z"
  generation: 6
  labels:
    app: webapp
    app.kubernetes.io/component: webapp
    app.kubernetes.io/instance: webapp
    app.kubernetes.io/name: webapp
  name: webapp
  namespace: anjulakshmi-dev
  resourceVersion: "4213357284"
  uid: 12bfb0d5-f3a4-4d36-b1c4-12787ac3d525
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: webapp
    spec:
      containers:
      - env:
        - name: DBHOST
          value: mysql
        - name: DB_NAME
          value: employees
        - name: DB_PASSWORD
          value: wpuserpass123
        - name: DB_USER
          value: wpuser
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: wpuser
        - name: DBPWD
          value: wpuserpass123
        - name: DATABASE
          value: employees
        - name: DBNAME
          value: employees
        image: image-registry.openshift-image-registry.svc:5000/anjulakshmi-dev/webapp@sha256:726b23398feed60ca2fdf377798d02559cd0b2804571ce4ebef7bc50feca0378
        imagePullPolicy: IfNotPresent
        name: webapp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-02T10:17:29Z"
    lastUpdateTime: "2025-11-02T10:17:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-11-02T10:06:43Z"
    lastUpdateTime: "2025-11-02T10:49:27Z"
    message: ReplicaSet "webapp-57476c4685" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
